export default {
    RESTAURANT_SELECTED: 'RESTAURANT_SELECTED',
    ADD_RESTAURANT: 'ADD_RESTAURANT',
    ADD_RESTAURANT_PENDING: 'ADD_RESTAURANT_PENDING',
    ADD_RESTAURANT_FULFILLED: 'ADD_RESTAURANT_FULFILLED',
    ADD_RESTAURANT_REJECTED: 'ADD_RESTAURANT_REJECTED',
    GET_GOOGLE_RESTAURANT_INFO: 'GET_GOOGLE_RESTAURANT_INFO',
    GET_GOOGLE_RESTAURANT_INFO_PENDING: 'GET_GOOGLE_RESTAURANT_INFO_PENDING',
    GET_GOOGLE_RESTAURANT_INFO_FULFILLED: 'GET_GOOGLE_RESTAURANT_INFO_FULFILLED',
    GET_GOOGLE_RESTAURANT_INFO_REJECTED: 'GET_GOOGLE_RESTAURANT_INFO_REJECTED',
    GET_ROOM_RESTAURANTS: 'GET_ROOM_RESTAURANTS',
    GET_ROOM_RESTAURANTS_PENDING: 'GET_ROOM_RESTAURANTS_PENDING',
    GET_ROOM_RESTAURANTS_FULFILLED: 'GET_ROOM_RESTAURANTS_FULFILLED',
    GET_ROOM_RESTAURANTS_INFO_REJECTED: 'GET_ROOM_RESTAURANTS_INFO_REJECTED'
}

