const GET_ROOMS = 'GET_ROOMS';
const GET_ROOMS_PENDING = 'GET_ROOMS_PENDING'
const GET_ROOMS_FULFILLED = 'GET_ROOMS_FULFILLED';
const GET_ROOMS_REJECTED = 'GET_ROOMS_REJECTED';

export default {
    GET_ROOMS,
    GET_ROOMS_PENDING,
    GET_ROOMS_FULFILLED,
    GET_ROOMS_REJECTED,
}