const GET_ROOMS = 'GET_ROOMS';
const GET_ROOMS_PENDING = 'GET_ROOMS_PENDING';
const GET_ROOMS_FULFILLED = 'GET_ROOMS_FULFILLED';
const GET_ROOMS_REJECTED = 'GET_ROOMS_REJECTED';
const CREATE_ROOM = 'CREATE_ROOM';
const CREATE_ROOM_PENDING = 'CREATE_ROOM_PENDING';
const CREATE_ROOM_FULFILLED = 'CREATE_ROOM_FULFILLED';
const CREATE_ROOM_REJECTED = 'CREATE_ROOM_REJECTED';
const JOIN_ROOM = 'JOIN_ROOM';
const JOIN_ROOM_PENDING = 'JOIN_ROOM_PENDING';
const JOIN_ROOM_FUFILLED = 'JOIN_ROOM_FUFILLED';
const JOIN_ROOM_REJECTED = 'JOIN_ROOM_REJECTED';
const JOIN_ROOM_UPDATED = 'JOIN_ROOM_UPDATED';
const NEW_ROOM_NAME = 'NEW_ROOM_NAME';
const NEW_ROOM_DESC = 'NEW_ROOM_DESC';
const SET_CURRENT_ROOM = 'SET_CURRENT_ROOM';

export default {
    GET_ROOMS,
    GET_ROOMS_PENDING,
    GET_ROOMS_FULFILLED,
    GET_ROOMS_REJECTED,
    CREATE_ROOM,
    CREATE_ROOM_PENDING,
    CREATE_ROOM_FULFILLED,
    CREATE_ROOM_REJECTED,
    JOIN_ROOM,
    JOIN_ROOM_PENDING,
    JOIN_ROOM_FUFILLED,
    JOIN_ROOM_REJECTED,
    JOIN_ROOM_UPDATED,
    NEW_ROOM_NAME,
    NEW_ROOM_DESC,
    SET_CURRENT_ROOM
};

