const GET_ROOMS = 'GET_ROOMS';
const GET_ROOMS_PENDING = 'GET_ROOMS_PENDING'
const GET_ROOMS_FULFILLED = 'GET_ROOMS_FULFILLED';
const GET_ROOMS_REJECTED = 'GET_ROOMS_REJECTED';
const CREATE_ROOM = 'CREATE_ROOM';
const CREATE_ROOM_PENDING = 'CREATE_ROOM_PENDING';
const CREATE_ROOM_FULFILLED = 'CREATE_ROOM_FULFILLED';
const CREATE_ROOM_REJECTED = 'CREATE_ROOM_REJECTED';

export default {
    GET_ROOMS,
    GET_ROOMS_PENDING,
    GET_ROOMS_FULFILLED,
    GET_ROOMS_REJECTED,
    CREATE_ROOM,
    CREATE_ROOM_PENDING,
    CREATE_ROOM_FULFILLED,
    CREATE_ROOM_REJECTED,
}