const SIGNUP = 'SIGNUP';
const SIGNUP_PENDING = 'SIGNUP_PENDING'
const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
const SIGNUP_REJECTED = 'SIGNUP_REJECTED';

export default {
    SIGNUP,
    SIGNUP_PENDING,
    SIGNUP_SUCCESS,
    SIGNUP_REJECTED,
}