export const SIGNUP = 'SIGNUP';
export const SIGNUP_PENDING = 'SIGNUP_PENDING'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_REJECTED = 'SIGNUP_REJECTED';

export const LOGIN_PENDING = "LOGIN_PENDING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_REJECTED = "LOGIN_REJECTED";
export const EMAIL_CHANGED = "EMAIL_CHANGED";
export const PASSWORD_CHANGED = "PASSWORD_CHANGED";

/*export default {
    SIGNUP,
    SIGNUP_PENDING,
    SIGNUP_SUCCESS,
    SIGNUP_REJECTED,
    LOGIN,
    LOGIN_PENDING,
    LOGIN_REJECTED,
    LOGIN_SUCCESS,
    EMAIL_CHANGED,
    PASSWORD_CHANGED
}*/