const SIGNUP = 'SIGNUP';
const SIGNUP_PENDING = 'SIGNUP_PENDING'
const SIGNUP_FULFILLED = 'SIGNUP_SUCCESS';
const SIGNUP_REJECTED = 'SIGNUP_REJECTED';
const LOGIN = 'LOGIN';
const LOGIN_PENDING = "LOGIN_PENDING";
const LOGIN_FULFILLED = "LOGIN_SUCCESS";
const LOGIN_REJECTED = "LOGIN_REJECTED";
const EMAIL_CHANGED = "EMAIL_CHANGED";
const PASSWORD_CHANGED = "PASSWORD_CHANGED";

export default {
    SIGNUP,
    SIGNUP_PENDING,
    SIGNUP_FULFILLED,
    SIGNUP_REJECTED,
    LOGIN,
    LOGIN_PENDING,
    LOGIN_REJECTED,
    LOGIN_FULFILLED,
    EMAIL_CHANGED,
    PASSWORD_CHANGED
}