const UPDATE_CHOICE = 'UPDATE_CHOICE';
const SUBMIT_VOTE = 'SUBMIT VOTE';
const UPDATE_RANKED_VOTE = 'UPDATE_RANKED_VOTE';
const SET_REDUX_ARRAY = "SET_REDUX_ARRAY";

export default {
    UPDATE_CHOICE,
    SUBMIT_VOTE,
    UPDATE_RANKED_VOTE,
    SET_REDUX_ARRAY,
};