const UPDATE_CHOICE = 'UPDATE_CHOICE';
const SINGLE_SUBMIT_VOTE = 'SINGLE_SUBMIT VOTE';
const RANKED_SUBMIT_VOTE = 'RANKED_SUMBIT_VOTE';
const UPDATE_RANKED_VOTE = 'UPDATE_RANKED_VOTE';
const SET_REDUX_ARRAY = "SET_REDUX_ARRAY";
const GET_ROOM_RESTAURANTS= 'GET_ROOM_RESTAURANTS';
const GET_ROOM_RESTAURANTS_PENDING= 'GET_ROOM_RESTAURANTS_PENDING';
const GET_ROOM_RESTAURANTS_FULFILLED= 'GET_ROOM_RESTAURANTS_FULFILLED';
const GET_ROOM_RESTAURANTS_REJECTED= 'GET_ROOM_RESTAURANTS_REJECTED';
const GET_GOOGLE_RESTAURANT_INFO= 'GET_GOOGLE_RESTAURANT_INFO';
const GET_GOOGLE_RESTAURANT_INFO_PENDING= 'GET_GOOGLE_RESTAURANT_INFO_PENDING';
const GET_GOOGLE_RESTAURANT_INFO_FULFILLED= 'GET_GOOGLE_RESTAURANT_INFO_FULFILLED';
const GET_GOOGLE_RESTAURANT_INFO_REJECTED= 'GET_GOOGLE_RESTAURANT_INFO_REJECTED';
const CLEAR_VOTING_STATE = 'CLEAR_VOTING_STATE';
const START_VOTE = 'START_VOTE';
const START_VOTE_FULFILLED = 'START_VOTE_FULFILLED';
const UPDATE_VOTING_STATE = 'UPDATE_VOTING_STATE';
const SUBMIT_READY = 'SUBMIT_READY';

export default {
    UPDATE_CHOICE,
    SINGLE_SUBMIT_VOTE,
    RANKED_SUBMIT_VOTE,
    UPDATE_RANKED_VOTE,
    SET_REDUX_ARRAY,
    GET_ROOM_RESTAURANTS,
    GET_ROOM_RESTAURANTS_FULFILLED,
    GET_ROOM_RESTAURANTS_PENDING,
    GET_ROOM_RESTAURANTS_REJECTED,
    GET_GOOGLE_RESTAURANT_INFO,
    GET_GOOGLE_RESTAURANT_INFO_PENDING,
    GET_GOOGLE_RESTAURANT_INFO_FULFILLED,
    GET_GOOGLE_RESTAURANT_INFO_REJECTED,
    CLEAR_VOTING_STATE,
    START_VOTE,
    START_VOTE_FULFILLED,
    UPDATE_VOTING_STATE,
    SUBMIT_READY,
};