const UPDATE_CHOICE = 'UPDATE_CHOICE';
const SINGLE_SUBMIT_VOTE = 'SINGLE_SUBMIT VOTE';
const RANKED_SUBMIT_VOTE = 'RANKED_SUMBIT_VOTE';
const UPDATE_RANKED_VOTE = 'UPDATE_RANKED_VOTE';
const SET_REDUX_ARRAY = "SET_REDUX_ARRAY";

export default {
    UPDATE_CHOICE,
    SINGLE_SUBMIT_VOTE,
    RANKED_SUBMIT_VOTE,
    UPDATE_RANKED_VOTE,
    SET_REDUX_ARRAY,
};